name: Build

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      cantaloupe-version: ${{ steps.cantaloupe-version.outputs.cantaloupe-version }}
    steps:
      - uses: actions/checkout@v4
      # This seems to work faster than pulling during docker compose up
      - name: Pull images
        run: docker compose pull --quiet
      - name: Bring up image image-server
        run: docker compose up --wait
      - name: Test image-server tif source -> jpg
        run: curl -fI http://localhost:8182/iiif/2/515698v2_fig1.tif/full/full/0/default.jpg
      - name: Test image-server gif source -> jpg
        run: curl -fI http://localhost:8182/iiif/2/515698v2_ueqn1.gif/full/full/0/default.jpg
      - name: Test image-server tif source -> png
        run: curl -fI http://localhost:8182/iiif/2/515698v2_fig1.tif/full/full/0/default.png
      - name: Test image-server gif source -> png
        run: curl -fI http://localhost:8182/iiif/2/515698v2_ueqn1.gif/full/full/0/default.png
      - id: cantaloupe-version
        name: Get cantaloupe version
        run: echo "cantaloupe-version=$(docker compose run -q --rm image-server bash -c 'echo $CANTALOUPE_VERSION')" >> $GITHUB_OUTPUT


  generate-version:
    runs-on: ubuntu-latest
    outputs:
      trunkver: ${{ steps.trunkver.outputs.trunkver }}
    steps:
      - name: Get a version tag
        id: trunkver
        uses: crftd-tech/trunkver@main
        with:
          prerelease: ${{ github.ref == 'refs/heads/master' && 'false' || 'true' }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: [generate-version, test]
    if: github.ref == 'refs/heads/master'
    env:
        IMAGE_REPO: ghcr.io/elifesciences/cantaloupe
        IMAGE_TAG: ${{ needs.generate-version.outputs.trunkver }}+${{ needs.test.outputs.cantaloupe-version }} #append Cantaloupe version in semver build info
    steps:
      - uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date --utc +%Y%m%d.%H%M)"
      - name: Get sha with 8 chars long
        id: commit_sha
        run: echo "::set-output name=commit_sha::${GITHUB_SHA:0:8}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # dependencies needed for building are amd64 only
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
